services:
  eureka:
    build: ./microservice-discovery-eureka
    ports:
      - "8761:8761"
    expose:
      - 8761
  provider-user:
    build: ./microservice-provider-user
    ports:
      - "8001:8001"
    expose:
      - 8001
    depends-on:
      - eureka
    links:
      - eureka